# Generated by Django 6.0.5 on 2026-05-31 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_booking_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the transaction was successfully finalized.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(help_text='Contact email for sending the booking confirmation and QR ticket.', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(help_text='Full name of the person under whom the booking is made.', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Dynamically generated QR code containing the booking payload.', null=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.CharField(help_text="Comma-separated string of allocated seat numbers (e.g., 'A1,A2,A3').", max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(help_text='The final calculated amount paid for this transaction.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of when this movie was added to the database.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(help_text='A detailed synopsis or plot summary of the movie.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(help_text="Total runtime of the movie (e.g., '2h 15m').", max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(help_text='The official poster or promotional banner for the movie.', upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.IntegerField(help_text='The base price for a single ticket.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='The official title of the movie.', max_length=200),
        ),
    ]
